/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proto.h"
#include <unistd.h>
#include <dirent.h>

int 
verificationInformations(struct svc_req *rq)
{
	switch(rq->rq_cred.oa_flavor)
	{
		case AUTH_UNIX:
			printf("AUTH_UNIX\n");
			struct authunix_parms* aup = (struct authunix_parms *) rq->rq_clntcred;
			printf("uid serveur : %d \n", getuid());
			printf("uid client : %d\n", aup->aup_uid);
			return 0;
		default :
			printf("AUTH_NULL\n");
			return 1;
	}
}


ls_res * 
ls_1_svc(type_nom *argp, struct svc_req *rqstp){
	printf("ls demandé\n");
	static ls_res  result;
	result.erreur=0;
	result.erreur=verificationInformations(rqstp);
	if(result.erreur!=0)
	{
		return &result;
	}
	DIR *repertoire;
	struct dirent *infosReadDir;
	cell_nom *cell1;
	cell_nom *cell2;
	repertoire = opendir(*argp);
	if(repertoire==NULL)
	{
		perror("Erreur ouverture dossier");
		result.erreur=2;
		return &result;
	}
	cell1=malloc(10*sizeof(char));
	cell2=cell1;
	result.ls_res_u.liste=cell1;

	while ((infosReadDir = readdir(repertoire)) != NULL)
	{	
		cell1->suivant=cell2;
		cell1=cell2;
		cell1->nom=calloc(MAXNOM,sizeof(char));
		cell1->suivant=NULL;
		strcpy(cell1->nom, infosReadDir->d_name);
		cell2=malloc(sizeof(cell_nom));
	}
	closedir(repertoire);	
	xdr_free((xdrproc_t)xdr_type_nom,(char*)argp);
	return &result;	
}

read_res * 
read_1_svc(type_nom *argp, struct svc_req *rqstp)
{
	printf("read demandé\n");
	static read_res  result;
	result.erreur=0;
	result.erreur=verificationInformations(rqstp);
	if(result.erreur!=0)
	{
		result = result;
		return &result;
	}

	FILE *file;
	char buffer[MAXBLOC];
	struct dirent *infosReadDir;
	cell_bloc *cell1;
	cell_bloc *cell2;
	file = fopen(*argp,"r");
	if(file==NULL) 
	{
		result.erreur=2;
		return &result;
	}
	cell1=calloc(1,sizeof(cell_bloc));
	cell1->bloc=calloc(MAXBLOC,sizeof(char));
	cell1->suivant=NULL;
	cell2=cell1;
	result.read_res_u.fichier=cell1;
	while (fgets(buffer, MAXBLOC, file)!=NULL)
	{
		cell1->suivant=cell2;
		cell1=cell2;
		cell1->bloc= calloc(MAXBLOC,sizeof(char));
		cell1->suivant=NULL;
		strcpy(cell1->bloc, buffer);
		cell2=calloc(MAXBLOC,sizeof(char));
	}
	fclose(file);	
	xdr_free((xdrproc_t)xdr_type_nom,(char*)argp);
	return &result;
}

int *
write_1_svc(write_parm *argp, struct svc_req *rqstp)
{
	printf("read demandé\n");
	static int  result;
	result=0;
	
	result=verificationInformations(rqstp);
	if(result!=0)
	{
		return &result;
	}

	FILE *file;
	char* fichier=argp->nom;
	cell_bloc *cell1 = argp->donnees;

	if( ! argp->ecraser)
	{
		file = fopen(fichier,"a");
	}
	else
	{
		file = fopen(fichier,"w");
	}
	
	if(file==NULL)
	{
		result=3;
		return &result;
	}

	while(cell1!=NULL)
	{	
		fputs(cell1->bloc,file);
		cell1=cell1->suivant;
	}
	fclose(file);
	xdr_free((xdrproc_t)xdr_write_parm,(char*)argp);
	return &result;
}